version: '3.8'
services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.83.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 127.0.0.1:1888:1888 # pprof extension
      - 127.0.0.1:8888:8888 # Prometheus metrics exposed by the collector
      - 127.0.0.1:8889:8889 # Prometheus exporter metrics
      - 127.0.0.1:13133:13133 # health_check extension
      - 127.0.0.1:4317:4317 # OTLP gRPC receiver
      - 127.0.0.1:4318:4318 # OTLP http receiver
      - 127.0.0.1:55679:55679 # zpages extension

  prometheus:
    image: prom/prometheus:v2.46.0
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 127.0.0.1:9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.48.0
    ports:
      - 127.0.0.1:16686:16686 # Web HTTP
      - 127.0.0.1:14250:14250 # Collector gRPC
    environment:
      COLLECTOR_OTLP_ENABLED: true
