scrape_configs:
- job_name: otel-collector-frontend
  scrape_interval: 10s
  static_configs:
  - targets:
    - otelcol:8889
- job_name: otel-collector-backend
  scrape_interval: 10s
  static_configs:
  - targets:
    - otelcol:8888
- job_name: server
  scrape_interval: 10s
  static_configs:
  - targets:
    - host.docker.internal:8000
